---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks

      - id: check-json
      - id: check-yaml
      - id: check-yaml
      - id: check-toml

      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

      - id: name-tests-test

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|yml|yaml|json)$
        exclude: (\.github/release-please-manifest\.json|CHANGELOG\.md)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
        exclude: poetry.lock$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: local
    hooks:
      - id: format
        name: format
        description: Format code
        entry: make format
        language: system
        pass_filenames: false
        always_run: true

      - id: lint
        name: lint
        description: Lint code
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
