style: github
template: CHANGELOG.md.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/jooola/gh-release-install
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - ci
  commit_groups:
    title_maps:
      feat: ":rocket: Features"
      fix: ":bug: Bug Fixes"
      ci: ":gear: CI/CD"
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
