name: Releaser-pleaser

on:
  push:
    branches: [main]
  pull_request_target:
    types:
      - edited
      - labeled
      - unlabeled

concurrency:
  group: releaser-pleaser

jobs:
  releaser-pleaser:
    # Do not run on forks.
    if: github.repository == 'jooola/gh-release-install'

    runs-on: ubuntu-latest
    steps:
      - name: releaser-pleaser
        uses: apricote/releaser-pleaser@v0.8.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          extra-files: |
            pyproject.toml
